"""
Django settings for apex_reports project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Os ajustes de produção vêm do ambiente — na VPS o systemd carrega
# /etc/apex-reports/env (ver deploy/deploy.sh). O padrão daqui é PRODUÇÃO, não
# desenvolvimento: um env faltando ou uma variável apagada à mão derruba a
# aplicação em vez de publicá-la com DEBUG ligado e a chave que está no
# GitHub. Quem liga o modo de desenvolvimento é o `manage.py`, que é a porta
# de entrada do dev — `python manage.py runserver` sem nenhuma variável
# continua funcionando como antes.

# SECURITY WARNING: don't run with debug turned on in production!
# Só os valores conhecidos ligam: variável vazia ou com lixo cai em desligado,
# que é o lado seguro de errar.
DEBUG = os.environ.get("DJANGO_DEBUG", "").strip().lower() in ("1", "true", "yes", "on")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY não definida. Em produção ela vem de "
            "/etc/apex-reports/env, que o deploy/deploy.sh escreve — rode o "
            "deploy de novo se o arquivo se perdeu. Não há chave embutida "
            "para cair: uma chave no repositório é uma chave pública."
        )
    # Fixa, e não sorteada a cada import, para a sessão sobreviver ao reload do
    # runserver — o fluxo de duas etapas morreria a cada arquivo salvo.
    SECRET_KEY = "django-insecure-somente-para-desenvolvimento-local"

# Em produção recebe o IP da VPS. Sem a variável ficam só os endereços locais:
# publicar sem informá-la devolve 400 em vez de atender por qualquer nome.
ALLOWED_HOSTS = [h.strip() for h in
                 os.environ.get("DJANGO_ALLOWED_HOSTS",
                                "localhost,127.0.0.1").split(",") if h.strip()]

# Subcaminho em que a aplicação é publicada (ex.: /apex-reports). O nginx tira o
# prefixo antes de repassar, então é daqui que o Django aprende a recolocá-lo em
# tudo que ele gera: {% url %}, redirects e {% static %}. Vazio em dev = raiz.
FORCE_SCRIPT_NAME = os.environ.get("DJANGO_SCRIPT_NAME", "").rstrip("/") or None

# Com prefixo, os cookies ficam restritos a ele: outra aplicação no mesmo IP tem
# seu próprio sessionid/csrftoken e os dois não se sobrescrevem.
if FORCE_SCRIPT_NAME:
    SESSION_COOKIE_PATH = FORCE_SCRIPT_NAME
    CSRF_COOKIE_PATH = FORCE_SCRIPT_NAME


# Application definition

# Só o que a aplicação usa de fato. Saíram as baterias que vieram do
# `startproject` e nunca foram ligadas: `admin` (nenhum modelo para
# administrar — ver apex_reports/urls.py), `auth` e `contenttypes` (a
# aplicação não tem login próprio; quem barra o acesso é o basic auth do
# nginx) e `messages` (nenhum template lê a fila). Cada uma trazia tabela,
# middleware e processador de contexto para não fazer nada.
#
# `sessions` fica: é ela que liga a etapa de importação à de revisão, e é o
# único motivo de existir banco aqui — `migrate` continua obrigatório.
INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'relatorios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apex_reports.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'apex_reports.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Sem AUTH_PASSWORD_VALIDATORS: não há senha que a aplicação valide — ela não
# tem cadastro nem login. A senha do painel é a do basic auth do nginx, criada
# pelo `htpasswd` no deploy/deploy.sh.


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Destino do `collectstatic` em produção — na VPS fica fora do projeto, em
# /var/www, para o nginx servir os estáticos sem precisar de permissão dentro
# da pasta pessoal do usuário que roda a aplicação.
STATIC_ROOT = Path(os.environ.get("DJANGO_STATIC_ROOT", BASE_DIR / 'staticfiles'))

# Logo servido tanto no PDF (lido do disco) quanto na interface web (via
# {% static %}) a partir de uma única fonte: docs/img/.
STATICFILES_DIRS = [BASE_DIR / 'docs' / 'img']
